"""
SyntheticParser — for testing and demo only.
Reads the AcademicIQ synthetic PDF format generated by the data generator.
NEVER used for real university PDFs.
"""
from __future__ import annotations

import json
import re

import pdfplumber
import structlog

from app.parsers.base import BaseParser, ExtractedRecord

logger = structlog.get_logger(__name__)

SYNTHETIC_MARKER = "ACADEMICIQ-SYNTHETIC"


class SyntheticParser(BaseParser):
    """
    Parses PDFs generated by the AcademicIQ synthetic data generator.
    Confidence is 0.99 for synthetic PDFs, 0.0 for all others.

    NOT FOR REAL DATA. Clearly labeled synthetic.
    """
    name = "SyntheticParser"
    version = "1.0"

    def can_parse(self, file_path: str) -> tuple[bool, float]:
        try:
            with pdfplumber.open(file_path) as pdf:
                if pdf.pages:
                    text = pdf.pages[0].extract_text() or ""
                    if SYNTHETIC_MARKER in text:
                        return True, 0.99
        except Exception:
            pass
        return False, 0.0

    def extract(self, file_path: str) -> list[ExtractedRecord]:
        records: list[ExtractedRecord] = []
        try:
            with pdfplumber.open(file_path) as pdf:
                for page_num, page in enumerate(pdf.pages, start=1):
                    tables = page.extract_tables()
                    for table in tables:
                        if not table or len(table) < 2:
                            continue
                        header = [str(c).strip().lower() if c else "" for c in table[0]]
                        if "register" not in " ".join(header):
                            continue
                        for row in table[1:]:
                            rec = self._parse_synthetic_row(row, header, page_num)
                            if rec:
                                records.append(rec)
        except Exception as e:
            logger.error("synthetic_parser_error", error=str(e))
        self.last_confidence = 0.99
        return records

    def _parse_synthetic_row(self, row, header, page_num) -> ExtractedRecord | None:
        def col(name: str) -> str | None:
            for i, h in enumerate(header):
                if name in h and i < len(row):
                    v = row[i]
                    return str(v).strip() if v else None
            return None

        reg = col("register")
        if not reg:
            return None

        raw_int = col("internal")
        raw_ext = col("external")
        raw_tot = col("total")
        _, int_absent = self._normalize_marks(raw_int)
        _, ext_absent = self._normalize_marks(raw_ext)

        return ExtractedRecord(
            raw_register_number=reg,
            raw_subject_code=col("subject") or col("code"),
            raw_subject_name=col("subject name"),
            raw_internal_marks=raw_int,
            raw_external_marks=raw_ext,
            raw_total_marks=raw_tot,
            raw_grade=col("grade"),
            raw_result_status=col("result") or col("status"),
            is_absent=(int_absent and ext_absent),
            page_number=page_num,
            extraction_method="table",
            confidence_score=0.99,
        )
