"""Initial schema — all tables.

Revision ID: 001_initial_schema
Revises:
Create Date: 2026-10-07
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # All tables are created via SQLAlchemy's create_all in tests/seed.
    # In production, run: alembic upgrade head
    # This migration is a placeholder; actual DDL is auto-generated by Alembic
    # from the models. Run `alembic revision --autogenerate -m "initial"` after
    # connecting to a live database to produce the full DDL.
    pass


def downgrade() -> None:
    pass
